13 successful tests overall
NikitaDunyashenko/SauceDemo_Tests pull request #5
Opened 2023-01-09 19:27 UTC by NikitaDunyashenko

2023-01-09 19:35 UTC, voropa requested changes

2023-01-09 19:35 UTC, voropa commented on src/test/java/pages/CheckoutPage.java
> +    public void fillingCheckoutForm() {
Во-первых, все тестовые дангные должны передааваться взодными агрументами в функции.
Во-вторых у вас же еуже есть ниже точно такой же метод, который принимает входные аргументы и заполняет ими поля ввода, зачем создавать еще один такой же метод?

2023-01-09 19:53 UTC, NikitaDunyashenko commented on src/test/java/pages/CheckoutPage.java
> +    public void fillingCheckoutForm() {
Логично. Я просто сначала сделал позитивный тест, а потом подумал, что негативный с data-driven тоже будет неплохо сделать. Исправлю. Еще хотел у Вас завтра спросить по поводу пары аннотаций в allure, чтобы репорт был более информативным. После этого доделаю все так, чтобы выглядело красивым проектом

2023-01-15 10:17 UTC, voropa approved these changes

2023-01-15 22:54 UTC, merged